CREATE DATABASE IF NOT EXISTS NODE_API_DATABASE;
CREATE OR REPLACE USER 'NODE_API_USER'@'%' IDENTIFIED BY 'NODE_API_PASSWORD';
GRANT ALL PRIVILEGES ON NODE_API_DATABASE.* TO 'NODE_API_USER'@'%';
FLUSH PRIVILEGES;
